import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

List<Map<String, dynamic>> dataTopCamps() {
  return [
    {
      "name": "Surf Camp - Villa Beach Party",
      "type": "Adventure",
      "country": "Portugal",
      "region": "Lisbonne",
      "city": "Lisbonne",
      "location": "Surf Camp - Villa Beach Party",
      "level_required": "Débutant",
      "description": "Détendez-vous et surfez sous le soleil de Lisbonne dans une ambiance festive.",
      "price": 450,
      "activities": ["Surf", "Fêtes", "Visites culturelles"],
      "amenities": ["Piscine", "Bar", "Accès direct à la plage"],
      "rating": 4.3,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/12/dji_0579-2048x1536-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/03/dsc_5841.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/98266132_1843848935739509_3101406261082587136_n-1024x682.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surfcamp-barbacue-night.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/breakfast-included-in-2.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/lisbonne/caparica-adulte/"
    },
    {
      "name": "Ocean Adventure, Natural Park Resort",
      "type": "Aventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Natural Park Resort",
      "level_required": "Intermédiaire",
      "description": "Explorez les merveilles naturelles de Dakhla avec des activités nautiques.",
      "price": 520,
      "activities": ["Kitesurf", "Exploration", "Yoga"],
      "amenities": ["Équipement sportif", "Spa", "Restaurant gastronomique"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/08/natural-park-resort-dakhla-chambre-1200.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/12/heliophora-double.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/12/heliophora-3-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/12/dsc01163.1800x1000-1-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/natural-park-resort-dakhla-kitecenter-2.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/kite-camp-lagon-8/"
    },

    {
      "name": "Beach Party: Kitecamp Economique et festif",
      "type": "Adventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Beach Party",
      "level_required": "Débutant",
      "description": "Un camp économique pour les amateurs de kitesurf avec des soirées festives.",
      "price": 300,
      "activities": ["Kitesurf", "Parties", "Musique"],
      "amenities": ["Bar", "Equipement de surf"],
      "rating": 4.2,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/09/beach-party-kitecamp-economique-et-festif-chambre-1024x608.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/beach-party-kitecamp-economique-et-festif-chambre-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/beach-party-kitecamp-economique-et-festif-dakhla-chambre-4-1024x676.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/beach-party-kitecamp-economique-et-festif-dakhla-chambre-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/beach-party-kitecamp-economique-et-festif-dakhla-chambre-5.jpg",
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/camp-6/"
    },
    {
      "name": "Ocean Adventure, Le Cercle Dakhla",
      "type": "Aventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Le Cercle",
      "level_required": "Intermédiaire",
      "description": "Explorez les eaux cristallines de Dakhla et profitez d'une aventure inoubliable.",
      "price": 500,
      "activities": ["Kitesurf", "Exploration marine", "Yoga"],
      "amenities": ["Restaurant", "Spa", "WiFi"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/08/le-cercle-terrasse.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/le-cercle-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/room-cercle.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/le-cercle.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/le-cercle-dakhlaa.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/room-cercle-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/resto-cercle-1-815x1024.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/kite-camp-18/"
    },
    {
      "name": "Ocean Adventure Le Lagon, Kite camp Dakhla",
      "type": "Aventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Le Lagon",
      "level_required": "Avancé",
      "description": "Un camp avancé pour les passionnés de kitesurf cherchant à améliorer leurs compétences.",
      "price": 550,
      "activities": ["Kitesurf avancé", "Competitions"],
      "amenities": ["Pro-shop", "Coaching personnalisé"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2021/08/14795.jpeg",
        "https://oceanadventure.surf/wp-content/uploads/2022/05/img_8131-ph-rosalia-filippetti-800x533-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/ocean-adventure-kitesurf-resort-dakhla-le-lagon-les-cours_hebergement-11-e1692606695568-1024x701.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/05/img_8131-ph-rosalia-filippetti-800x533-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/ocean-adventure-kitesurf-resort-dakhla-le-lagon-les-cours_hebergement-4-e1692604956913.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/dakhla-lagon-dejeuner-e1692607443646.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/kite-camp-lagon-7/"
    },
    {
      "name": "Ocean Adventure Lassarga : Lagune et Océan",
      "type": "Aventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Lassarga",
      "level_required": "Débutant",
      "description": "Profitez de la beauté naturelle de Lassarga pour une expérience complète de kitesurf.",
      "price": 450,
      "activities": ["Kitesurf", "Yoga", "Balades nature"],
      "amenities": ["Eco-lodges", "Restauration bio"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/10/lassarga-kite-1024x685.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/kite-camp-ocean-adventure-lassarga-3-1-1024x679.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/lassarga-beach-bar-1024x684.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/capture-decran-2024-01-05-103934.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/beach-bar-lassarga-1024x681.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/lassarga/"
    },
    {
      "name": "Kitecamp - Fuerteventura, Corralejo",
      "type": "Aventure",
      "country": "Canaries",
      "region": "Fuerteventura",
      "city": "Corralejo",
      "location": "Kitecamp Corralejo",
      "level_required": "Intermédiaire",
      "description": "Découvrez le frisson du kitesurf dans les magnifiques plages de Corralejo.",
      "price": 400,
      "activities": ["Kitesurf", "Snorkeling"],
      "amenities": ["Magasin de surf", "Cours personnalisés"],
      "rating": 4.5,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-6.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1024x768.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/canaries/fuerteventura-2/corralejo/"
    },
    {
      "name": "Surf camp Surf House, Imsouane - Maroc",
      "type": "Relax",
      "country": "Maroc",
      "region": "Imsouane",
      "city": "Imsouane",
      "location": "Surf House",
      "level_required": "Débutant",
      "description": "Apprenez à surfer dans les vagues parfaites d'Imsouane, idéal pour débutants et familles.",
      "price": 320,
      "activities": ["Surf", "Yoga", "Ateliers de surf"],
      "amenities": ["École de surf", "Restaurant", "Vue sur mer"],
      "rating": 4.6,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/10/brahim-imsouane.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/imsouane-surf-house-e1707833322628-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/imsouane-2/surf-camp-1/"
    },
    {
      "name": "Surfcamp Surf house Bilbao",
      "type": "Aventure",
      "country": "Espagne",
      "region": "Pays Basque",
      "city": "Bilbao",
      "location": "Surf House",
      "level_required": "Intermédiaire",
      "description": "Plongez dans la culture du surf basque avec ce camp situé au cœur de Bilbao.",
      "price": 340,
      "activities": ["Surf", "Visites culturelles", "Gastronomie"],
      "amenities": ["Ateliers de surf", "Tours guidés", "Hébergement urbain"],
      "rating": 4.4,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-surf-yoga-spa-1-1024x576.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/foto-exterior-nocturna-encuadre-mas-cerrado-baja-1-1024x702.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-surf-yoga-spa-13-1-1024x682.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/dsc_1383-1-1-1024x681.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-surf-yoga-spa-12-1024x576.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/espagne/bilbao/"
    },
    {
      "name": "Le meilleur Surf Camp d'Imsouane",
      "type": "Adventure",
      "country": "Maroc",
      "region": "Imsouane",
      "city": "Imsouane",
      "location": "Meilleur Surf Camp",
      "level_required": "Tous niveaux",
      "description": "Vivez une expérience de surf inoubliable avec des instructeurs de renommée mondiale.",
      "price": 500,
      "activities": ["Surf avancé", "Photographie de surf", "Relaxation"],
      "amenities": ["Suites de luxe", "Piscine à débordement", "Spa"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2024/01/imsouane-3225-1024x686.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/01/suite-vue-mer-1024x666.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/03/tsm20.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/imsouane-activites-960x750.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/04/telechargement-4-960x551.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/imsouane-2/"
    },
    {
      "name": "Surf Lodge Premium",
      "type": "View",
      "country": "Maroc",
      "region": "Taghazout",
      "city": "Taghazout",
      "location": "Surf Lodge Premium",
      "level_required": "Avancé",
      "description": "Expérience de surf de luxe avec des vues imprenables sur l'océan et des cours personnalisés.",
      "price": 650,
      "activities": ["Surf", "Yoga", "Relaxation"],
      "amenities": ["Spa", "Restaurant gourmet", "Piscine chauffée"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/01/surfnfriends.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/322748542.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/358131410_18065484433406269_2684752630181068356_n1-1024x1024.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/272429876_648068799973142_1697168591816504879_n-1024x1024.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/367432326_18070897126406269_3885384719068672346_n-1024x1024.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/taghazout/surf-camp-8/"
    },
    {
      "name": "Surf camp Taghazout - Maroc Authentique",
      "type": "Culture",
      "country": "Maroc",
      "region": "Taghazout",
      "city": "Taghazout",
      "location": "Maroc Authentique",
      "level_required": "Tous niveaux",
      "description": "Immergez-vous dans la culture marocaine tout en profitant des meilleures vagues.",
      "price": 420,
      "activities": ["Surf", "Cours de cuisine marocaine", "Visites culturelles"],
      "amenities": ["Hébergement traditionnel", "Marché local"],
      "rating": 4.6,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/11/caption-6-1024x1024-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/06/rooftop-7-of-1-11.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/06/caption-5-1024x1024.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/06/caption-7.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/06/repas-au-meilleur-surf-camp-economique-de-taghazout-scaled-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/taghazout/surf-camp-2/"
    },
    {
      "name": "Séjour ados et Colonies",
      "type": "Family",
      "country": "France",
      "region": "Pays Basque",
      "city": "Biarritz",
      "location": "Colonies Biarritz",
      "level_required": "Débutant",
      "description": "Camp d'été pour adolescents axé sur l'apprentissage du surf et des activités de groupe.",
      "price": 300,
      "activities": ["Surf", "Jeux de plage", "Excursions"],
      "amenities": ["Encadrement", "Activités de groupe"],
      "rating": 4.4,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/05/photo047.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/31659430.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/93760843.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/93760946.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/134957088.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/biarritz-pays-basque/hebergement-groupes/"
    },
    {
      "name": "Surfcamp - Fuerteventura, Corralejo",
      "type": "Aventure",
      "country": "Canaries",
      "region": "Fuerteventura",
      "city": "Corralejo",
      "location": "Fuerteventura Surfcamp",
      "level_required": "Intermédiaire",
      "description": "Surfcamp dynamique à Fuerteventura avec des instructeurs expérimentés et un équipement de pointe.",
      "price": 400,
      "activities": ["Surf", "Kitesurf", "Volleyball de plage"],
      "amenities": ["Bar de plage", "Location de matériel"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-6.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1024x768.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/canaries/fuerteventura-2/surfcamp/"
    },
    {
      "name": "Surf Camp Sidi Kaouki - Villa Beach House",
      "type": "Adventure",
      "country": "Maroc",
      "region": "Sidi Kaouki",
      "city": "Sidi Kaouki",
      "location": "Villa Beach House",
      "level_required": "Tous niveaux",
      "description": "Profitez d'un séjour Adventure dans notre villa sur la plage avec des sessions de surf guidées.",
      "price": 600,
      "activities": ["Surf", "Yoga au coucher du soleil", "Balades à cheval"],
      "amenities": ["Villa privée", "Chef personnel", "Piscine"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/08/surfcamp-sidi-kouaki-villa-sarah-image-8.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/surfcamp-sidi-kouaki-villa-sarah-image-9.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/surfcamp-sidi-kouaki-villa-chambre-e1708438321698.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/essaouira/villa-perchee/"
    },
    {
      "name": "Boutique Hôtel Surf And Yoga House",
      "type": "Relax",
      "country": "Maroc",
      "region": "Taghazout",
      "city": "Taghazout",
      "location": "Boutique Hôtel",
      "level_required": "Tous niveaux",
      "description": "Combinez surf et yoga dans notre boutique hôtel pour une relaxation ultime et un entraînement complet.",
      "price": 700,
      "activities": ["Surf", "Yoga", "Méditation"],
      "amenities": ["Spa", "Cours de yoga", "Équipement de surf de haute qualité"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/04/25373764-8829-4983-939f-0c0d9dd36584_1_201_a.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/dsc_4698-1024x684.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/376298730.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/376298645.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/376298748.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/f9538cdb-d8ab-498f-9e07-58e312d7d706-1152x1536.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/taghazout/surf-camp-6/"
    },
    {
      "name": "Ocean Adventure, Nature & Spa",
      "type": "Relax",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Nature & Spa",
      "level_required": "Tous niveaux",
      "description": "Détendez-vous dans notre spa après une journée d'aventure océanique dans les eaux de Dakhla.",
      "price": 800,
      "activities": ["Kitesurf", "Spa", "Yoga"],
      "amenities": ["Spa de luxe", "Piscine", "Restaurant gastronomique"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/09/kitecamp-nature-et-spa-ocean-adventure-1024x576.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/dakhla-desrt-pool-e1692778667601-1-1024x811.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/piscine-tour-dakhla-e1692778199216-1024x816.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/10/nature-spa-terrasse-1-1024x814.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/10/img_4722-1024x618.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/diner-romantique-1-1024x1024.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/camp-5/"
    },
    {
      "name": "Ocean Vagabond Le Lagon, Dakhla",
      "type": "Adventure",
      "country": "Maroc",
      "region": "Dakhla",
      "city": "Dakhla",
      "location": "Ocean Vagabond",
      "level_required": "Débutant à Intermédiaire",
      "description": "Profitez de notre camp Éco-responsable avec une vue imprenable sur le lagon de Dakhla.",
      "price": 550,
      "activities": ["Kitesurf", "Eco-tours", "Yoga"],
      "amenities": ["Hébergement écologique", "Restaurant bio", "Ateliers sur l'environnement"],
      "rating": 4.6,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/02/capture-decran-2023-02-08-111301-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/pacha-lodge-dakhla2-1-e1708425085334.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/03/young-blood1-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/431652580.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/03/431657810.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/dakhla/camp-2/"
    },
    {
      "name": "Surfcamp - La Centrale",
      "type": "Family",
      "country": "France",
      "region": "Landes",
      "city": "Hossegor",
      "location": "La Centrale",
      "level_required": "Débutant à Avancé",
      "description": "Idéal pour jeunes surfeurs souhaitant améliorer leurs compétences dans les vagues landaises.",
      "price": 450,
      "activities": ["Surf", "Compétitions junior", "Activités de groupe"],
      "amenities": ["Coaching", "Hébergement proche de la plage", "Activités nocturnes"],
      "rating": 4.5,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2024/05/286270141-1024x682.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/06/sans-titre-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/250440541.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/154777320.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/jo-joe-hossegor.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/jo-joe-hossegor-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/france-2/hossegor/surf-camp-3/"
    },
    {
      "name": "Surf Camp Nazaré, Portugal",
      "type": "Adventure",
      "country": "Portugal",
      "region": "Nazaré",
      "city": "Nazaré",
      "location": "Surf Camp Nazaré",
      "level_required": "Avancé",
      "description": "Défiez les plus grandes vagues du monde à Nazaré avec notre équipe de surfeurs professionnels.",
      "price": 750,
      "activities": ["Surf de gros", "Coaching avancé", "Analyse vidéo"],
      "amenities": ["Accès direct aux spots de gros", "Équipement de sécurité", "Analyse vidéo"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/02/284856318_706396327320985_8471395624122156538_n.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/103003521.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/104383572.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/103003476.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/0094e6_8c35cc25ea1c4e4ba27e882b04e1b908_mv2-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/nazare/"
    },
    {
      "name": "Surf Lodge Péniche, Portugal",
      "type": "Family",
      "country": "Portugal",
      "region": "Peniche",
      "city": "Peniche",
      "location": "Surf Lodge",
      "level_required": "Tous niveaux",
      "description": "Un camp familial offrant une expérience de surf complète pour tous les âges à Peniche.",
      "price": 500,
      "activities": ["Surf", "Ateliers pour enfants", "Excursions locales"],
      "amenities": ["Hébergement familial", "Cours de surf pour tous les âges", "Piscine"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/06/dsc05271-1-scaled-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/as4-1024x686.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/04/447804471-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/surf-camp-peniche-1024x576.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/04/91909535-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/peniche-baleal/surf-camp-1/"
    },
    {
      "name": "Auberge Bilbao",
      "type": "Culturel",
      "country": "Espagne",
      "region": "Pays Basque",
      "city": "Bilbao",
      "location": "Auberge Bilbao",
      "level_required": "Débutant",
      "description": "Explorez la culture basque tout en apprenant à surfer dans les vagues de Bilbao.",
      "price": 320,
      "activities": ["Surf", "Visites culturelles", "Gastronomie locale"],
      "amenities": ["Guides locaux", "Cours de surf débutant", "Hébergement en auberge"],
      "rating": 4.3,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2024/01/17113185.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-auberge-authentique-ocean-adventure1-1024x680.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-auberge-authentique-ocean-adventure1-1024x680.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surfcamp-bilbao-auberge-authentique-ocean-adventure-3-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/09/surf-camp-de-bilbao-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/espagne/bilbao/surfhotel/"
    },
    {
      "name": "Surf camp Surf & Chill Capbreton – Hossegor",
      "type": "Relax",
      "country": "France",
      "region": "Landes",
      "city": "Hossegor",
      "location": "Capbreton",
      "level_required": "Débutant",
      "description": "Détendez-vous et surfez dans les vagues douces de Hossegor, parfait pour débutants et amateurs de chill.",
      "price": 460,
      "activities": ["Surf", "Yoga", "Relaxation"],
      "amenities": ["Spa", "Yoga studio", "Bar lounge"],
      "rating": 4.6,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/05/145976365.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/145976500.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/2019_wnslexterieur2-1920w.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/2019_wnslexterieur4-1920w.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/2019_wnslcuisine-1024x573.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/196930341.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/france-2/surf-camp-4/"
    },
    {
      "name": "Surfcamp - Surf House Adventure",
      "type": "Adventure",
      "country": "France",
      "region": "Landes",
      "city": "Capbreton",
      "location": "Surf House",
      "level_required": "Avancé",
      "description": "Améliorez votre technique de surf avec des coachs professionnels dans un environnement dédié à la Performance.",
      "price": 500,
      "activities": ["Surf avancé", "Coaching personnalisé", "Analyse vidéo"],
      "amenities": ["Gym", "Analyse vidéo", "Équipement pro"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2020/02/surf-camp-hossegor-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/terrasse-1600-x-1560-1-a20aa46e.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/1600-x-200x0y-oga-0bf56ac2-1200x1500.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/salon1600-x-1560-98b57e85.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/1600-x-200x0spa-3129d45d-1200x1500.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/france-2/hossegor/surf-camp-2/"
    },
    {
      "name": "Surf Camp Villa - Beach House Corralejo",
      "type": "Relax",
      "country": "Canaries",
      "region": "Fuerteventura",
      "city": "Corralejo",
      "location": "Villa Beach House",
      "level_required": "Tous niveaux",
      "description": "Profitez du luxe et du confort de notre villa en bord de mer avec accès direct aux meilleures vagues.",
      "price": 750,
      "activities": ["Surf", "Relaxation", "Snorkeling"],
      "amenities": ["Villa privée", "Piscine", "Accès plage privée"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2022/10/dsc02399-w1100h550-1024x512.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-villa-beach-house-a-corralejo-3.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-villa-beach-house-a-corralejo-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-villa-beach-house-a-corralejo-7-1024x768.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-villa-beach-house-a-corralejo-11-2-1024x707.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/canaries/fuerteventura-2/corralejo-2/"
    },
    {
      "name": "Winf Foil camp - Fuerteventura, Corralejo",
      "type": "Adventure",
      "country": "Canaries",
      "region": "Fuerteventura",
      "city": "Corralejo",
      "location": "Winf Foil Camp",
      "level_required": "Intermédiaire",
      "description": "Découvrez la nouvelle sensation de glisse avec notre camp de Wind Foil, idéal pour ceux cherchant à repousser les limites.",
      "price": 680,
      "activities": ["Wind Foil", "Kitesurf", "Fitness marin"],
      "amenities": ["Équipement moderne", "Coaching", "Ateliers"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-7-1024x683-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/wing-kite-flag-beach-1024x576.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-8.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/surf-camp-fuerteventura-corralejo-iles-canaries-1024x768.jpg",
      ],
      "booking_link": "https://oceanadventure.surf/canaries/wingfoil/"
    },
    {
      "name": "Village Vacances Surf à Corralejo",
      "type": "Family",
      "country": "Canaries",
      "region": "Fuerteventura",
      "city": "Corralejo",
      "location": "Village Vacances",
      "level_required": "Débutant",
      "description": "Parfait pour les familles, notre village de vacances offre des activités surf adaptées à tous les âges.",
      "price": 520,
      "activities": ["Surf", "Activités enfants", "Excursions"],
      "amenities": ["Club enfants", "Animations", "Restauration familiale"],
      "rating": 4.5,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-village-fuerteventura-img-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-village-fuerteventura-img3.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-village-fuerteventura-img2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-village-fuerteventura-img-6-1024x768.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-village-fuerteventura-img-9-1024x768.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/canaries/fuerteventura-2/surf-village/"
    },
    {
      "name": "Surf Camp Vue Mer Peniche, Portugal",
      "type": "View",
      "country": "Portugal",
      "region": "Peniche",
      "city": "Peniche",
      "location": "Vue Mer",
      "level_required": "Débutant à Intermédiaire",
      "description": "Découvrez le surf avec une vue imprenable sur l'océan Atlantique dans l'un des meilleurs spots de surf de Portugal.",
      "price": 530,
      "activities": ["Surf", "Stand Up Paddle", "Beach Volley"],
      "amenities": ["Terrasse avec vue", "Accès direct à la plage", "Bar"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/02/room1-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/02/surfcastle__013-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/04/c939c0b8-4280-4c98-930b-f42396c1ee69.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/02/055968eb-f561-45b1-a896-c3898dcff652.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/02/064b186d-5a14-432c-bafb-f0ef984f9715.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/peniche-baleal/surf-camp-4/"
    },
    {
      "name": "Surf Camp Yoga & Chill – Peniche, Portugal",
      "type": "Relax",
      "country": "Portugal",
      "region": "Peniche",
      "city": "Peniche",
      "location": "Yoga & Chill",
      "level_required": "Tous niveaux",
      "description": "Combinez yoga et surf pour une relaxation profonde et une amélioration de votre technique de surf.",
      "price": 600,
      "activities": ["Yoga", "Surf", "Méditation"],
      "amenities": ["Studio de yoga", "Spa", "Instructeurs certifiés"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2024/02/surf-yoga-resort-peniche.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/653x490-3.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/02/onsite-the-backyard-restaurant-1024x684.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/653x490-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/653x490-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/653x490-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/07/cc6a7b_f255a421fb114dd8ac7092a584af74af_mv2.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/peniche-baleal/surf-camp-5/"
    },
    {
      "name": "Kitecamp Obidos",
      "type": "Aventure",
      "country": "Portugal",
      "region": "Obidos",
      "city": "Obidos",
      "location": "Kitecamp",
      "level_required": "Intermédiaire à Avancé",
      "description": "Relevez de nouveaux défis et améliorez vos compétences en kitesurf dans les magnifiques eaux d'Obidos.",
      "price": 650,
      "activities": ["Kitesurf", "Wakeboard", "Compétitions"],
      "amenities": ["École de kite", "Location d'équipement", "Hébergement confortable"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/12/kite-wing-camp-a-obidos-image-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/kite-wing-camp-a-obidos-image-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/kite-wing-camp-a-obidos-image-5.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/kite-wing-camp-a-obidos-image-3.jpg",
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/peniche-baleal/kite-camp-obidos/"
    },
    {
      "name": "Surf House - Açores",
      "type": "Adventure",
      "country": "Portugal",
      "region": "Açores",
      "city": "Ponta Delgada",
      "location": "Surf House",
      "level_required": "Débutant",
      "description": "Profitez d'une ambiance Adventure pour apprendre le surf dans le cadre spectaculaire des Açores.",
      "price": 570,
      "activities": ["Surf", "Écotourisme", "Randonnée"],
      "amenities": ["Éco-lodges", "Guides locaux", "Cuisine locale"],
      "rating": 4.6,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2022/03/triki_surfhouse_rooms_rs_170620_0037-1536x1024.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/surf-camp-azores-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/acores2-1024x575.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/yoga-acores-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/284160375.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/portugal-2/acores/surfcamp-1/"
    },
    {
      "name": "Resort Sicile",
      "type": "Culturel",
      "country": "Italie",
      "region": "Sicile",
      "city": "Stagone",
      "location": "Resort",
      "level_required": "Débutant à Intermédiaire",
      "description": "Découvrez le charme unique de la Sicile tout en profitant de sessions de surf exceptionnelles.",
      "price": 690,
      "activities": ["Surf", "Découverte culturelle", "Gastronomie"],
      "amenities": ["Spa", "Excursions", "Gastronomie locale"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/04/residence-santa-maria-1-1024x683.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/double-room-sea-view-1-.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/pool-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/appartamento-con-vista-min-1024x681.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/04/residence-santa-maria-1-1024x683.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/europe/sicile/surf-camp-1/"
    },
    {
      "name": "Wingfoil, Surf & Yoga Camp Essaouira, Maroc",
      "type": "Relax",
      "country": "Maroc",
      "region": "Essaouira",
      "city": "Essaouira",
      "location": "Wingfoil and Surf",
      "level_required": "Intermédiaire",
      "description": "Combinez surf, yoga et wingfoil pour une expérience sportive et relaxante à Essaouira.",
      "price": 620,
      "activities": ["Surf", "Wingfoil", "Yoga"],
      "amenities": ["Ateliers de yoga", "Équipement wingfoil", "Spa"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/07/surf-camp-de-wingfoil-essaouira-1-ocean-adventure.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/ocean-adventure-com-surfing2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/ocean-adventure-come-surfing.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/08/ocean-adventure-come-surfing-3.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/dejeuneressaouira-1024x823.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/essaouira/surf-camp-1/"
    },
    {
      "name": "Surfcamp Banana Village, Taghazout Bay",
      "type": "Family",
      "country": "Maroc",
      "region": "Taghazout",
      "city": "Taghazout",
      "location": "Banana Village",
      "level_required": "Débutant",
      "description": "Idéal pour les familles, découvrez le surf dans l'atmosphère détendue de Banana Village.",
      "price": 480,
      "activities": ["Surf", "Ateliers pour enfants", "Yoga"],
      "amenities": ["Club enfants", "Piscine", "Restaurant"],
      "rating": 4.5,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/10/surf-camp-agadir-ocean-adventure-6.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/img_7550-1-1152x1536.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/surfbananavillage.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/10/surf-camp-agadir-ocean-adventure-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/10/surf-camp-agadir-ocean-adventure-9.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/taghazout/surf-camp-12/"
    },
    {
      "name": "Le meilleur Surf Camp de Taghazout, Maroc",
      "type": "View",
      "country": "Maroc",
      "region": "Taghazout",
      "city": "Taghazout",
      "location": "Meilleur Surf Camp",
      "level_required": "Avancé",
      "description": "Vivez une expérience de surf inégalée dans le meilleur camp de Taghazout, avec des coaches de renommée internationale.",
      "price": 750,
      "activities": ["Surf avancé", "Coaching personnalisé", "Yoga"],
      "amenities": ["Accès VIP aux spots", "Hébergement de luxe", "Restauration bio"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/02/gl8.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/gl29-1024x684.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/gl2-1024x684.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/gl14.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/195851125.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/maroc/taghazout/surf-camp-10/t"
    },
    {
      "name": "Surf Camp - Jungle view, Santa Teresa",
      "type": "Aventure",
      "country": "Costa Rica",
      "region": "Santa Teresa",
      "city": "Santa Teresa",
      "location": "Jungle view",
      "level_required": "Tous niveaux",
      "description": "Immergez-vous dans la nature luxuriante de Santa Teresa tout en profitant de sessions de surf exceptionnelles.",
      "price": 680,
      "activities": ["Surf", "Trekking", "Yoga"],
      "amenities": ["Vue jungle", "Espaces de détente", "Cours de surf"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2022/04/sta-teresa-surfcamp.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/12/surf-house-jungle-view-1024x682.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2022/12/montezuma-cabuya-nicoya-costa-rica-1024x558.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/surf-house-playa-hermosa-santa-teresa-img-1-1024x576.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2021/01/costa-rica-960x750.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/costa-rica/santa-teresa/"
    },
    {
      "name": "Surfcamp Canggu, Bali, Indonésie",
      "type": "Culture",
      "country": "Indonésie",
      "region": "Bali",
      "city": "Canggu",
      "location": "Surfcamp Canggu",
      "level_required": "Intermédiaire",
      "description": "Explorez les vagues paradisiaques de Canggu avec notre surfcamp trendy et ses instructeurs passionnés.",
      "price": 700,
      "activities": ["Surf", "Yoga", "Visites culturelles"],
      "amenities": ["Cours de surf personnalisés", "Piscine à débordement", "Bar de plage"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/07/surfcamp-canggu-12-ocean-adventure.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/07/surfcamp-canggu-2-ocean-adventure.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/12/surf-camp-canggu-bali-indonesie.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/07/surfcamp-canggu-12-ocean-adventure.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/07/surfcamp-canggu-9-ocean-adventure.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/asie/indonesie/bali/canggu2/"
    },
    {
      "name": "Surfcamp Ado de Luxe",
      "type": "Relax",
      "country": "France",
      "region": "Pays Basque",
      "city": "Biarritz",
      "location": "Ado de Luxe",
      "level_required": "Débutant à Intermédiaire",
      "description": "Un camp de surf Adventure pour adolescents, offrant une formation de haute qualité et des activités de luxe dans la magnifique région de Biarritz.",
      "price": 800,
      "activities": ["Surf", "Ateliers de cuisine", "Sorties culturelles"],
      "amenities": ["Hébergement de luxe", "Piscine", "Service complet"],
      "rating": 4.8,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/03/location-villa-biarritz-avec-piscine-locaction-villa-lux-biarritz-avec-piscine-scaled-min-1024x768.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/chambre-milady-biarritz-scaled-min.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/chambre-marbella-biarritz-pays-basque-scaled-min.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/01/surf-camp-ados-deluxe-biarritz-2.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/03/capture-decran-2023-02-24-120003-1-1024x768.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/surf-camp-ados/deluxe-biarritz/"
    },
    {
      "name": "Surf Camp - Beach House",
      "type": "Family",
      "country": "France",
      "region": "Gironde",
      "city": "Lacanau",
      "location": "Beach House",
      "level_required": "Tous niveaux",
      "description": "Situé directement sur la plage, notre camp propose une immersion totale dans le surf avec une vue imprenable sur l'océan à Lacanau.",
      "price": 650,
      "activities": ["Surf", "Paddleboard", "Beach games"],
      "amenities": ["Accès direct à la plage", "Hébergement en bord de mer", "Cours de surf"],
      "rating": 4.7,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2024/07/surf-camp-lacanau-221-1024x536.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/05/img-4507-1536x2048-min-1152x1536.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/06/lacanau-surf-camp-1024x730.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/04/surf-camp-lacanau-5-1024x1024.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/france-2/gironde/surf-camp-lacanau/"
    },
    {
      "name": "Surfcamp Ados",
      "type": "Family",
      "country": "France",
      "region": "Pays-de-la-Loire",
      "city": "Sables d'olonnes",
      "location": "Surfcamp Ados",
      "level_required": "Débutant",
      "description": "Ce camp pour jeunes propose des cours de surf et une multitude d'activités pour garantir un été inoubliable aux Sables d'Olonne.",
      "price": 450,
      "activities": ["Surf", "Kayak", "Jeux de plage"],
      "amenities": ["Moniteurs jeunesse", "Activités de groupe", "Camping"],
      "rating": 4.5,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/11/image-surf-camp-ados-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/image-surf-camp-ados-4.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/image-surf-camp-ados-3.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/image-surf-camp-ados-bar-et-restaurant-1.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/11/groupe-surfcamp-ado-vendee-1024x683-1.jpg"
      ],
      "booking_link": "https://oceanadventure.surf/france-2/la-tranche/surf-camp-ados-1/"
    },
    {
      "name": "Surf Camp - Villa Beach Party",
      "type": "Adventure",
      "country": "Sri Lanka",
      "region": "Ahangama",
      "city": "Ahangama",
      "location": "Villa Beach",
      "level_required": "Tous niveaux",
      "description": "Vivez la fête ultime sur la plage dans notre villa exclusivement située à Ahangama, avec des cours de surf quotidiens et des soirées inoubliables.",
      "price": 700,
      "activities": ["Surf", "Fêtes sur la plage", "BBQ"],
      "amenities": ["Villa privée", "Piscine", "Accès plage direct"],
      "rating": 4.9,
      "image_urls": [
        "https://oceanadventure.surf/wp-content/uploads/2023/12/ahangama-sri-lanka-1024x763.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2023/02/villa-beach-party-e1677513128642.jpg",
        "https://oceanadventure.surf/wp-content/uploads/2024/02/1440_6e0-1635949941-1-1024x764.jpg",
      ],
      "booking_link": "https://oceanadventure.surf/asie/sri-lanka/surf-camp-1/"
    }
  ];
}

