import 'package:cloud_firestore/cloud_firestore.dart';

List<Map<String, dynamic>> simulateDataEtapesWingfoil() {
  return [
    {
      'id': 1.1,
      'description': 'Règles de sécurité de base',
      'name': 'BEGINNER - 1.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/-HTkf1UXjiE',
    },
    {
      'id': 1.2,
      'description': 'Mise en place de l\'aile',
      'name': 'BEGGINER - 1.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/y4RfRN9V4tY',
    },
    {
      'id': 1.3,
      'description': 'Contrôle de l\'aile',
      'name': 'BEGINNER - 1.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/rLOI-XK1M_Y',
    },
    {
      'id': 1.4,
      'description': 'Commencer à sourire sur un longboard',
      'name': 'BEGINNER - 1.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/E7mLr4DX284',
    },
    {
      'id': 1.5,
      'description': 'Pilotage avec l\'aile',
      'name': 'BEGINNER - 2.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ceOf57SEK74',
    },
    {
      'id': 1.6,
      'description': 'Naviguer sur différents parcours',
      'name': 'BEGINNER - 2.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/isNluAUp6VQ',
    },
    {
      'id': 1.7,
      'description': 'Virer de bord et empanner',
      'name': 'BEGINNER - 2.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/isNluAUp6VQ',
    },
    {
      'id': 1.8,
      'description': 'Remonter au vent',
      'name': 'BEGINNER - 2.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/t_-9aWM-KUE',
    },
    {
      'id': 1.9,
      'description': 'Règles de priorité dans la navigation',
      'name': 'BEGINNER - 2.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/31hUD1HJEVA',
    },
    {
      'id': 2.1,
      'description': 'Règles de sécurité du foil',
      'name': 'INTERMEDIATE - 3.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/bb1Xt7hJPz0',
    },
    {
      'id': 2.2,
      'description': 'Sécurité de navigation sur un foil',
      'name': 'INTERMEDIATE - 3.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ZoNO6jFEiSs',
    },
    {
      'id': 2.3,
      'description': 'Pilotage avec la planche',
      'name': 'INTERMEDIATE - 3.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ZoNO6jFEiSs',
    },
    {
      'id': 2.4,
      'description': 'Foil sur différents parcours',
      'name': 'INTERMEDIATE - 3.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/76T0sEVcglA',
    },
    {
      'id': 2.5,
      'description': 'Apprentissage des transitions',
      'name': 'ADVANCED - 5.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/dK9HRdHp4M4',
    },
    {
      'id': 2.6,
      'description': 'Apprentissage des tricks',
      'name': 'ADVANCED - 5.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/OrCtWTpHx-M',
    },
    {
      'id': 2.7,
      'description': 'Apprentissage du surf avec l\'aile',
      'name': 'ADVANCED - 5.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/kXo0Ez06m1Y',
    },
    {
      'id': 2.8,
      'description': 'Sauts et figures',
      'name': 'ADVANCED - 5.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/BbqbdrHyxM8',
    },
    {
      'id': 2.9,
      'description': 'Techniques avancées de navigation',
      'name': 'PRO - 6.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/3wNqfV6g1Vo',
    },
    {
      'id': 3.1,
      'description': 'Maîtrise des sauts et figures',
      'name': 'PRO - 6.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/N9XyevsLsM4',
    },
    {
      'id': 3.2,
      'description': 'Gestion de l\'aile dans des conditions extrêmes',
      'name': 'PRO - 6.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/UO4OQT4_GZg',
    },
    {
      'id': 3.3,
      'description': 'Compétition de wingfoil',
      'name': 'PRO - 6.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/lZIzBVFoDn0',
    },
  ];
}
