import 'package:cloud_firestore/cloud_firestore.dart';

List<Map<String, dynamic>> simulateDataEtapesWingfoil() {
  return [
    {
      'id': 1.1,
      'description': 'Règles de sécurité de base',
      'name': 'BEGINNER - 1.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/-HTkf1UXjiE',
    },
    {
      'id': 1.2,
      'description': 'Mise en place de l\'aile',
      'name': 'BEGGINER - 1.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/y4RfRN9V4tY',
    },
    {
      'id': 1.3,
      'description': 'Contrôle de l\'aile',
      'name': 'BEGINNER - 1.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/rLOI-XK1M_Y',
    },
    {
      'id': 1.4,
      'description': 'Commencer à sourire sur un longboard',
      'name': 'BEGINNER - 1.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/E7mLr4DX284',
    },
    {
      'id': 1.5,
      'description': 'Pilotage avec l\'aile',
      'name': 'BEGINNER - 2.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ceOf57SEK74',
    },
    {
      'id': 1.6,
      'description': 'Naviguer sur différents parcours',
      'name': 'BEGINNER - 2.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/isNluAUp6VQ',
    },
    {
      'id': 1.7,
      'description': 'Virer de bord et empanner',
      'name': 'BEGINNER - 2.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/isNluAUp6VQ',
    },
    {
      'id': 1.8,
      'description': 'Remonter au vent',
      'name': 'BEGINNER - 2.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/t_-9aWM-KUE',
    },
    {
      'id': 1.9,
      'description': 'Règles de priorité dans la navigation',
      'name': 'BEGINNER - 2.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/31hUD1HJEVA',
    },
    {
      'id': 2.1,
      'description': 'Règles de sécurité du foil',
      'name': 'INTERMEDIATE - 3.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/bb1Xt7hJPz0',
    },
    {
      'id': 2.2,
      'description': 'Sécurité de navigation sur un foil',
      'name': 'INTERMEDIATE - 3.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ZoNO6jFEiSs',
    },
    {
      'id': 2.3,
      'description': 'Pilotage avec la planche',
      'name': 'INTERMEDIATE - 3.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/ZoNO6jFEiSs',
    },
    {
      'id': 2.4,
      'description': 'Foil sur différents parcours',
      'name': 'INTERMEDIATE - 3.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/76T0sEVcglA',
    },
    {
      'id': 2.5,
      'description': 'Apprentissage des transitions',
      'name': 'ADVANCED - 5.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/dK9HRdHp4M4',
    },
    {
      'id': 2.6,
      'description': 'Apprentissage des tricks',
      'name': 'ADVANCED - 5.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/OrCtWTpHx-M',
    },
    {
      'id': 2.7,
      'description': 'Apprentissage du surf avec l\'aile',
      'name': 'ADVANCED - 5.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/kXo0Ez06m1Y',
    },
    {
      'id': 2.8,
      'description': 'Sauts et figures',
      'name': 'ADVANCED - 5.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/BbqbdrHyxM8',
    },
    {
      'id': 2.9,
      'description': 'Techniques avancées de navigation',
      'name': 'PRO - 6.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/3wNqfV6g1Vo',
    },
    {
      'id': 3.1,
      'description': 'Maîtrise des sauts et figures',
      'name': 'PRO - 6.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/N9XyevsLsM4',
    },
    {
      'id': 3.2,
      'description': 'Gestion de l\'aile dans des conditions extrêmes',
      'name': 'PRO - 6.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/UO4OQT4_GZg',
    },
    {
      'id': 3.3,
      'description': 'Compétition de wingfoil',
      'name': 'PRO - 6.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/4'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/1'),
      'video': 'https://youtu.be/lZIzBVFoDn0',
    },
  ];
}

List<Map<String, dynamic>> simulateDataEtapesKitesurf() {
  return [
    {
      'id': 3.4,
      'description': 'Sécurité de base',
      'name': 'DEBUTANT - 3.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/dIiO6O_X0xM',
    },
    {
      'id': 3.5,
      'description': 'Controller le kite sur le bord du pare-vent',
      'name': 'DEBUTANT - 3.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/hRN2FMwbnro',
    },
    {
      'id': 3.6,
      'description': 'Bodydragging',
      'name': 'DEBUTANT - 3.6',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://www.google.com/url?',
    },
    {
      'id': 3.7,
      'description': 'Powerdives?',
      'name': 'DEBUTANT - 3.7',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/YVwXKDBrG3A https://youtu.be/uLRIDxOBJzo',
    },
    {
      'id': 3.8,
      'description': 'Lancement et atterrissage',
      'name': 'DEBUTANT - 3.8',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/etBeG_-CkGw',
    },
    {
      'id': 3.9,
      'description': 'Récupération de bord',
      'name': 'DEBUTANT - 3.9',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/ViaeO-pX9F0',
    },
    {
      'id': 4.1,
      'description': 'Premiers démarrages à l\'eau',
      'name': 'DEBUTANT - 4.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/YNWCqwfN5Qk',
    },
    {
      'id': 4.2,
      'description': 'Relancer',
      'name': 'DEBUTANT - 4.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/sQ7FtY3QXHg',
    },
    {
      'id': 4.3,
      'description': 'Aller dans les deux directions',
      'name': 'DEBUTANT - 4.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/lE-ahreablU',
    },
    {
      'id': 4.4,
      'description': 'S\'arrêter',
      'name': 'DEBUTANT - 4.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/X97Lz3FM7R0',
    },
    {
      'id': 4.5,
      'description': 'Règles de priorité',
      'name': 'DEBUTANT - 4.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/vX0qQI6TOqc',
    },
    {
      'id': 4.6,
      'description': 'Controller la vitesse de planche et la direction',
      'name': 'INTERMEDIAIRE - 4.6',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/sHfM6uGzWPc',
    },
    {
      'id': 4.7,
      'description': 'Gérer les vents légers',
      'name': 'INTERMEDIAIRE - 4.7',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/9XlErYz5LGk',
    },
    {
      'id': 4.8,
      'description': 'Naviguer en remontant le vent',
      'name': 'INTERMEDIAIRE - 4.8',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/6BfVvbDQH8s',
    },
    {
      'id': 4.9,
      'description': 'Sauter en hauteur',
      'name': 'INTERMEDIAIRE - 4.9',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/ah7tjEKQdC0',
    },
    {
      'id': 5.1,
      'description': 'Faire des tricks de base',
      'name': 'AVANCE - 5.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/1TtVLXm-9jg',
    },
    {
      'id': 5.2,
      'description': 'Faire des sauts et rotations',
      'name': 'AVANCE - 5.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/wyWTrC5O5Ow',
    },
    {
      'id': 5.3,
      'description': 'Réaliser des tricks freestyle',
      'name': 'AVANCE - 5.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/XhldJjz_yvc',
    },
    {
      'id': 5.4,
      'description': 'Maîtriser les manœuvres de transition',
      'name': 'AVANCE - 5.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/03n0eXjKfFY',
    },
    {
      'id': 5.5,
      'description': 'Surfer des vagues',
      'name': 'AVANCE - 5.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/2'),
      'video': 'https://youtu.be/8ZU6XPAX1ZE',
    },
  ];
}

List<Map<String, dynamic>> simulateDataEtapesSurf() {
  return [
    {
      'id': 5.6,
      'description': 'Sécurité de base',
      'name': 'DEBUTANT - 5.6',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/dIiO6O_X0xM',
    },
    {
      'id': 5.7,
      'description': 'Controller le kite sur le bord du pare-vent',
      'name': 'DEBUTANT - 5.7',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/hRN2FMwbnro',
      'priority': 2,
      'createdAt': '2023-04-19 08:57:02',
      'updatedAt': '2023-04-19 08:57:02',
    },
    {
      'id': 5.8,
      'description': 'Bodydragging',
      'name': 'DEBUTANT - 5.8',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': '',
    },
    {
      'id': 5.9,
      'description': 'Powerdives?',
      'name': 'DEBUTANT - 5.9',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/YVwXKDBrG3A https://youtu.be/uLRIDxOBJzo',
    },
    {
      'id': 6.1,
      'description': 'Lancement et atterrissage',
      'name': 'DEBUTANT - 6.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/etBeG_-CkGw',
    },
    {
      'id': 6.2,
      'description': 'Récupération de bord',
      'name': 'DEBUTANT - 6.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/ViaeO-pX9F0',
    },
    {
      'id': 6.3,
      'description': 'Premiers démarrages à l\'eau',
      'name': 'DEBUTANT - 6.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/YNWCqwfN5Qk',
    },
    {
      'id': 6.4,
      'description': 'Relancer',
      'name': 'DEBUTANT - 6.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/sQ7FtY3QXHg',
    },
    {
      'id': 6.5,
      'description': 'Aller dans les deux directions',
      'name': 'DEBUTANT - 6.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/lE-ahreablU',
    },
    {
      'id': 6.6,
      'description': 'S\'arrêter',
      'name': 'DEBUTANT - 6.6',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/X97Lz3FM7R0',
    },
    {
      'id': 6.7,
      'description': 'Règles de priorité',
      'name': 'DEBUTANT - 6.7',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/vX0qQI6TOqc',
    },
    {
      'id': 6.8,
      'description': 'Règles de priorité',
      'name': 'DEBUTANT - 6.8',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/1'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/vX0qQI6TOqc',
    },
    {
      'id': 6.9,
      'description': 'Controller la vitesse de planche et la direction',
      'name': 'INTERMEDIAIRE - 6.9',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/sHfM6uGzWPc',
    },
    {
      'id': 7.1,
      'description': 'Gérer les vents légers',
      'name': 'INTERMEDIAIRE - 7.1',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/9XlErYz5LGk',
    },
    {
      'id': 7.2,
      'description': 'Naviguer en remontant le vent',
      'name': 'INTERMEDIAIRE - 7.2',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/6BfVvbDQH8s',
    },
    {
      'id': 7.3,
      'description': 'Sauter en hauteur',
      'name': 'INTERMEDIAIRE - 7.3',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/2'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/ah7tjEKQdC0',
    },
    {
      'id': 7.4,
      'description': 'Faire des tricks de base',
      'name': 'AVANCE - 7.4',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/1TtVLXm-9jg',
    },
    {
      'id': 7.5,
      'description': 'Faire des sauts et rotations',
      'name': 'AVANCE - 7.5',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/wyWTrC5O5Ow',
    },
    {
      'id': 7.6,
      'description': 'Réaliser des tricks freestyle',
      'name': 'AVANCE - 7.6',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/XhldJjz_yvc',
    },
    {
      'id': 7.7,
      'description': 'Maîtriser les manœuvres de transition',
      'name': 'AVANCE - 7.7',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/03n0eXjKfFY',
    },
    {
      'id': 7.8,
      'description': 'Surfer des vagues',
      'name': 'AVANCE - 7.8',
      'niveauRef': FirebaseFirestore.instance.doc('/niveaux/3'),
      'sportRef': FirebaseFirestore.instance.doc('/sports/3'),
      'video': 'https://youtu.be/8ZU6XPAX1ZE',
    },
  ];
}
